name: Curse Build

on:
  push:
    tags:
      - '*'
    paths-ignore:
      - ".github/**"

env:
   CF_API_KEY: ${{ secrets.CF_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Create Classic Package
        uses: BigWigsMods/packager@master
        with:
          args: -g bcc -m .pkgmeta_classic_bc
      - name: Create Classic Era Package
        uses: BigWigsMods/packager@master
        with:
          args: -g classic -m .pkgmeta_classic
      - name: Create Retail Package
        uses: BigWigsMods/packager@master
        with:
          args: -g retail
